import {
  Column,
  CreateDateColumn,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { SellerOnboardingProgress } from './seller-onboarding-progress.entity';
import { StatusEnum } from '../../../common/enums/status.enum';
import { DocumentType } from '../../../common/enums/document.enum';

@Entity('seller_onboarding_documents')
export class SellerOnboardingDocument {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @ManyToOne(() => SellerOnboardingProgress, (progress) => progress.documents, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'onboarding_progress_id' })
  onboardingProgress!: SellerOnboardingProgress;

  @Column({ name: 'onboarding_progress_id', type: 'uuid' })
  onboardingProgressId!: string;

  @Column({
    type: 'enum',
    enum: DocumentType,
  })
  documentType!: DocumentType;

  @Column({ name: 'cloudinary_public_id', type: 'varchar', length: 500 })
  cloudinaryPublicId!: string;

  /**
   * Secure HTTPS URL from Cloudinary
   * Can be used directly in img tags
   * Includes CDN delivery
   *
   * Format: https://res.cloudinary.com/{account}/image/upload/{public_id}
   * Example: https://res.cloudinary.com/kopa/image/upload/seller/550e.../ID_FRONT
   */
  @Column({ name: 'cloudinary_url', type: 'text' })
  cloudinaryUrl!: string;

  /**
   * Secure thumbnail URL (small preview)
   * Auto-generated by Cloudinary
   * Used for admin dashboard previews
   *
   * Size: 200x200 pixels
   * Format: HTTPS
   */
  @Column({ name: 'cloudinary_thumbnail_url', type: 'text', nullable: true })
  cloudinaryThumbnailUrl!: string;

  /**
   * Original file name as uploaded by user
   * Example: "national_id_front.jpg"
   */
  @Column({
    name: 'original_file_name',
    type: 'varchar',
    length: 255,
    nullable: true,
  })
  originalFileName!: string;

  /**
   * File size in bytes
   * Used for validation (max 1MB)
   * For display: bytes / 1024 / 1024 = MB
   */
  @Column({ name: 'file_size', type: 'integer', nullable: true })
  fileSize!: number;

  /**
   * Image dimensions from Cloudinary
   * Format: "1920x1080" (width x height)
   */
  @Column({ type: 'varchar', length: 50, nullable: true })
  dimensions!: string;

  /**
   * Image format/MIME type
   * Examples: "jpg", "png", "webp"
   */
  @Column({ type: 'varchar', length: 20, nullable: true })
  format!: string;

  /**
   * Document verification status by admin
   * PENDING: Uploaded, awaiting admin review
   * APPROVED: Admin verified document is valid
   * REJECTED: Document rejected, needs resubmission
   *
   * Can be different from overall step status
   * E.g., ID_FRONT approved but ID_BACK rejected
   */
  @Column({
    name: 'verification_status',
    type: 'enum',
    enum: StatusEnum,
    default: StatusEnum.PENDING,
  })
  verificationStatus!: StatusEnum;

  /**
   * Why document was rejected (if applicable)
   * Admin notes explaining rejection reason
   */
  @Column({ name: 'rejection_reason', type: 'text', nullable: true })
  rejectionReason!: string;

  /**
   * Admin who reviewed this document
   * UUID of admin user
   */
  @Column({ name: 'reviewed_by_admin', type: 'uuid', nullable: true })
  reviewedByAdminId!: string;

  /**
   * When document was reviewed
   */
  @Column({ name: 'reviewed_at', type: 'timestamp', nullable: true })
  reviewedAt!: Date;

  /**
   * Cloudinary metadata (JSON)
   * Stores all Cloudinary response data
   * Useful for:
   * - Image analysis data
   * - OCR extracted text (if enabled)
   * - Color information
   * - EXIF data
   *
   * Example:
   * {
   *   "public_id": "seller/550e.../ID_FRONT",
   *   "width": 1920,
   *   "height": 1080,
   *   "format": "jpg",
   *   "created_at": "2024-01-01T12:00:00Z",
   *   "bytes": 245823,
   *   "url": "http://...",
   *   "secure_url": "https://...",
   *   "tags": ["seller", "id_verification"]
   * }
   */
  @Column({ name: 'cloudinary_metadata', type: 'jsonb', nullable: true })
  cloudinaryMetadata!: Record<string, any>;

  /**
   * Additional notes about the document
   * Admin can add notes during review
   */
  @Column({ name: 'admin_notes', type: 'text', nullable: true })
  adminNotes!: string;

  /**
   * When document was uploaded
   */
  @CreateDateColumn({ name: 'created_at' })
  createdAt!: Date;
}
